race_node:
  ros__parameters:
    laps: 7
    max_retries: 20

    # use_start=False : le planner prend la pose actuelle du robot via TF.
    use_start_for_first_segment: false

    tracks_file: "/home/voiture/bolide_voiture/config_nav2/tracks.yaml"
    active_track: "map_etage_2_cleaned"
